spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/shop
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/shop
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: shop-app
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email

keycloak:
  admin:
    server-url: http://localhost:8082
    realm: shop
    client-id: shop-app
    client-secret: rB3fiY3Ox04wXeW2YqseTp9dVJYLq7VJ

server:
  port: 8081

logging:
  level:
    org.springframework.security: TRACE
