spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/shop
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/shop
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: shop-app
            client-secret: GgAhA4dJEUeQH6Dyhf26Svz8p9Iyr2V8
            scope: openid
server:
  port: 8081
logging:
  level:
    org.springframework.security: TRACE


