spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/shop
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/shop
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: shop-app
            authorization-grant-type: authorization_code
            client-authentication-method: none    # <--- ВАЖНО! без него ЛОГИН НЕ БУДЕТ РАБОТАТЬ С PKCE
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email

keycloak:
  admin:
    server-url: http://localhost:8082
    realm: shop
    client-id: shop-admin
    client-secret: uF5u38F7pMNaY7Ca8wIbtmpRTM2h1fuv

server:
  port: 8081

logging:
  level:
    org.springframework.security: TRACE
